package com.example.mapper;

import com.example.bean.Classmates;
import com.example.bean.ClassmatesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ClassmatesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classmates
     *
     * @mbggenerated Wed Feb 28 18:21:08 CST 2018
     */
    int countByExample(ClassmatesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classmates
     *
     * @mbggenerated Wed Feb 28 18:21:08 CST 2018
     */
    int deleteByExample(ClassmatesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classmates
     *
     * @mbggenerated Wed Feb 28 18:21:08 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classmates
     *
     * @mbggenerated Wed Feb 28 18:21:08 CST 2018
     */
    int insert(Classmates record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classmates
     *
     * @mbggenerated Wed Feb 28 18:21:08 CST 2018
     */
    int insertSelective(Classmates record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classmates
     *
     * @mbggenerated Wed Feb 28 18:21:08 CST 2018
     */
    List<Classmates> selectByExample(ClassmatesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classmates
     *
     * @mbggenerated Wed Feb 28 18:21:08 CST 2018
     */
    Classmates selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classmates
     *
     * @mbggenerated Wed Feb 28 18:21:08 CST 2018
     */
    int updateByExampleSelective(@Param("record") Classmates record, @Param("example") ClassmatesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classmates
     *
     * @mbggenerated Wed Feb 28 18:21:08 CST 2018
     */
    int updateByExample(@Param("record") Classmates record, @Param("example") ClassmatesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classmates
     *
     * @mbggenerated Wed Feb 28 18:21:08 CST 2018
     */
    int updateByPrimaryKeySelective(Classmates record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classmates
     *
     * @mbggenerated Wed Feb 28 18:21:08 CST 2018
     */
    int updateByPrimaryKey(Classmates record);
}