package com.example.mapper;

import com.example.bean.UserToken;
import com.example.bean.UserTokenExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserTokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_token
     *
     * @mbggenerated Wed Feb 28 15:52:12 CST 2018
     */
    int countByExample(UserTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_token
     *
     * @mbggenerated Wed Feb 28 15:52:12 CST 2018
     */
    int deleteByExample(UserTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_token
     *
     * @mbggenerated Wed Feb 28 15:52:12 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_token
     *
     * @mbggenerated Wed Feb 28 15:52:12 CST 2018
     */
    int insert(UserToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_token
     *
     * @mbggenerated Wed Feb 28 15:52:12 CST 2018
     */
    int insertSelective(UserToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_token
     *
     * @mbggenerated Wed Feb 28 15:52:12 CST 2018
     */
    List<UserToken> selectByExample(UserTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_token
     *
     * @mbggenerated Wed Feb 28 15:52:12 CST 2018
     */
    UserToken selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_token
     *
     * @mbggenerated Wed Feb 28 15:52:12 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserToken record, @Param("example") UserTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_token
     *
     * @mbggenerated Wed Feb 28 15:52:12 CST 2018
     */
    int updateByExample(@Param("record") UserToken record, @Param("example") UserTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_token
     *
     * @mbggenerated Wed Feb 28 15:52:12 CST 2018
     */
    int updateByPrimaryKeySelective(UserToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_token
     *
     * @mbggenerated Wed Feb 28 15:52:12 CST 2018
     */
    int updateByPrimaryKey(UserToken record);
}