package com.example.bean;

import java.util.Date;

public class Classmates {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classmates.id
     *
     * @mbggenerated Wed Feb 28 18:21:08 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classmates.name
     *
     * @mbggenerated Wed Feb 28 18:21:08 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classmates.mobile
     *
     * @mbggenerated Wed Feb 28 18:21:08 CST 2018
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classmates.email
     *
     * @mbggenerated Wed Feb 28 18:21:08 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classmates.birthday
     *
     * @mbggenerated Wed Feb 28 18:21:08 CST 2018
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classmates.guaduated_school
     *
     * @mbggenerated Wed Feb 28 18:21:08 CST 2018
     */
    private String guaduatedSchool;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classmates.major
     *
     * @mbggenerated Wed Feb 28 18:21:08 CST 2018
     */
    private String major;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classmates.double_major
     *
     * @mbggenerated Wed Feb 28 18:21:08 CST 2018
     */
    private String doubleMajor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classmates.upgraded_school
     *
     * @mbggenerated Wed Feb 28 18:21:08 CST 2018
     */
    private String upgradedSchool;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classmates.city
     *
     * @mbggenerated Wed Feb 28 18:21:08 CST 2018
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classmates.company
     *
     * @mbggenerated Wed Feb 28 18:21:08 CST 2018
     */
    private String company;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classmates.id
     *
     * @return the value of classmates.id
     *
     * @mbggenerated Wed Feb 28 18:21:08 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classmates.id
     *
     * @param id the value for classmates.id
     *
     * @mbggenerated Wed Feb 28 18:21:08 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classmates.name
     *
     * @return the value of classmates.name
     *
     * @mbggenerated Wed Feb 28 18:21:08 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classmates.name
     *
     * @param name the value for classmates.name
     *
     * @mbggenerated Wed Feb 28 18:21:08 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classmates.mobile
     *
     * @return the value of classmates.mobile
     *
     * @mbggenerated Wed Feb 28 18:21:08 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classmates.mobile
     *
     * @param mobile the value for classmates.mobile
     *
     * @mbggenerated Wed Feb 28 18:21:08 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classmates.email
     *
     * @return the value of classmates.email
     *
     * @mbggenerated Wed Feb 28 18:21:08 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classmates.email
     *
     * @param email the value for classmates.email
     *
     * @mbggenerated Wed Feb 28 18:21:08 CST 2018
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classmates.birthday
     *
     * @return the value of classmates.birthday
     *
     * @mbggenerated Wed Feb 28 18:21:08 CST 2018
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classmates.birthday
     *
     * @param birthday the value for classmates.birthday
     *
     * @mbggenerated Wed Feb 28 18:21:08 CST 2018
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classmates.guaduated_school
     *
     * @return the value of classmates.guaduated_school
     *
     * @mbggenerated Wed Feb 28 18:21:08 CST 2018
     */
    public String getGuaduatedSchool() {
        return guaduatedSchool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classmates.guaduated_school
     *
     * @param guaduatedSchool the value for classmates.guaduated_school
     *
     * @mbggenerated Wed Feb 28 18:21:08 CST 2018
     */
    public void setGuaduatedSchool(String guaduatedSchool) {
        this.guaduatedSchool = guaduatedSchool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classmates.major
     *
     * @return the value of classmates.major
     *
     * @mbggenerated Wed Feb 28 18:21:08 CST 2018
     */
    public String getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classmates.major
     *
     * @param major the value for classmates.major
     *
     * @mbggenerated Wed Feb 28 18:21:08 CST 2018
     */
    public void setMajor(String major) {
        this.major = major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classmates.double_major
     *
     * @return the value of classmates.double_major
     *
     * @mbggenerated Wed Feb 28 18:21:08 CST 2018
     */
    public String getDoubleMajor() {
        return doubleMajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classmates.double_major
     *
     * @param doubleMajor the value for classmates.double_major
     *
     * @mbggenerated Wed Feb 28 18:21:08 CST 2018
     */
    public void setDoubleMajor(String doubleMajor) {
        this.doubleMajor = doubleMajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classmates.upgraded_school
     *
     * @return the value of classmates.upgraded_school
     *
     * @mbggenerated Wed Feb 28 18:21:08 CST 2018
     */
    public String getUpgradedSchool() {
        return upgradedSchool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classmates.upgraded_school
     *
     * @param upgradedSchool the value for classmates.upgraded_school
     *
     * @mbggenerated Wed Feb 28 18:21:08 CST 2018
     */
    public void setUpgradedSchool(String upgradedSchool) {
        this.upgradedSchool = upgradedSchool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classmates.city
     *
     * @return the value of classmates.city
     *
     * @mbggenerated Wed Feb 28 18:21:08 CST 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classmates.city
     *
     * @param city the value for classmates.city
     *
     * @mbggenerated Wed Feb 28 18:21:08 CST 2018
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classmates.company
     *
     * @return the value of classmates.company
     *
     * @mbggenerated Wed Feb 28 18:21:08 CST 2018
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classmates.company
     *
     * @param company the value for classmates.company
     *
     * @mbggenerated Wed Feb 28 18:21:08 CST 2018
     */
    public void setCompany(String company) {
        this.company = company;
    }
}