package com.example.bean;

import java.util.Date;

public class Message {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.id
     *
     * @mbggenerated Sun Jul 09 12:16:24 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.name
     *
     * @mbggenerated Sun Jul 09 12:16:24 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.description
     *
     * @mbggenerated Sun Jul 09 12:16:24 CST 2017
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.createdAt
     *
     * @mbggenerated Sun Jul 09 12:16:24 CST 2017
     */
    private Date createdat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.updatedAt
     *
     * @mbggenerated Sun Jul 09 12:16:24 CST 2017
     */
    private Date updatedat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.endAt
     *
     * @mbggenerated Sun Jul 09 12:16:24 CST 2017
     */
    private Date endat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.source
     *
     * @mbggenerated Sun Jul 09 12:16:24 CST 2017
     */
    private String source;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.id
     *
     * @return the value of message.id
     *
     * @mbggenerated Sun Jul 09 12:16:24 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.id
     *
     * @param id the value for message.id
     *
     * @mbggenerated Sun Jul 09 12:16:24 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.name
     *
     * @return the value of message.name
     *
     * @mbggenerated Sun Jul 09 12:16:24 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.name
     *
     * @param name the value for message.name
     *
     * @mbggenerated Sun Jul 09 12:16:24 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.description
     *
     * @return the value of message.description
     *
     * @mbggenerated Sun Jul 09 12:16:24 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.description
     *
     * @param description the value for message.description
     *
     * @mbggenerated Sun Jul 09 12:16:24 CST 2017
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.createdAt
     *
     * @return the value of message.createdAt
     *
     * @mbggenerated Sun Jul 09 12:16:24 CST 2017
     */
    public Date getCreatedat() {
        return createdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.createdAt
     *
     * @param createdat the value for message.createdAt
     *
     * @mbggenerated Sun Jul 09 12:16:24 CST 2017
     */
    public void setCreatedat(Date createdat) {
        this.createdat = createdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.updatedAt
     *
     * @return the value of message.updatedAt
     *
     * @mbggenerated Sun Jul 09 12:16:24 CST 2017
     */
    public Date getUpdatedat() {
        return updatedat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.updatedAt
     *
     * @param updatedat the value for message.updatedAt
     *
     * @mbggenerated Sun Jul 09 12:16:24 CST 2017
     */
    public void setUpdatedat(Date updatedat) {
        this.updatedat = updatedat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.endAt
     *
     * @return the value of message.endAt
     *
     * @mbggenerated Sun Jul 09 12:16:24 CST 2017
     */
    public Date getEndat() {
        return endat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.endAt
     *
     * @param endat the value for message.endAt
     *
     * @mbggenerated Sun Jul 09 12:16:24 CST 2017
     */
    public void setEndat(Date endat) {
        this.endat = endat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.source
     *
     * @return the value of message.source
     *
     * @mbggenerated Sun Jul 09 12:16:24 CST 2017
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.source
     *
     * @param source the value for message.source
     *
     * @mbggenerated Sun Jul 09 12:16:24 CST 2017
     */
    public void setSource(String source) {
        this.source = source;
    }
}