package com.example.bean;

import java.util.Date;

public class UserToken {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_token.id
     *
     * @mbggenerated Wed Feb 28 15:52:12 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_token.user_id
     *
     * @mbggenerated Wed Feb 28 15:52:12 CST 2018
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_token.token
     *
     * @mbggenerated Wed Feb 28 15:52:12 CST 2018
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_token.expired_at
     *
     * @mbggenerated Wed Feb 28 15:52:12 CST 2018
     */
    private Date expiredAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_token.id
     *
     * @return the value of user_token.id
     *
     * @mbggenerated Wed Feb 28 15:52:12 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_token.id
     *
     * @param id the value for user_token.id
     *
     * @mbggenerated Wed Feb 28 15:52:12 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_token.user_id
     *
     * @return the value of user_token.user_id
     *
     * @mbggenerated Wed Feb 28 15:52:12 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_token.user_id
     *
     * @param userId the value for user_token.user_id
     *
     * @mbggenerated Wed Feb 28 15:52:12 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_token.token
     *
     * @return the value of user_token.token
     *
     * @mbggenerated Wed Feb 28 15:52:12 CST 2018
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_token.token
     *
     * @param token the value for user_token.token
     *
     * @mbggenerated Wed Feb 28 15:52:12 CST 2018
     */
    public void setToken(String token) {
        this.token = token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_token.expired_at
     *
     * @return the value of user_token.expired_at
     *
     * @mbggenerated Wed Feb 28 15:52:12 CST 2018
     */
    public Date getExpiredAt() {
        return expiredAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_token.expired_at
     *
     * @param expiredAt the value for user_token.expired_at
     *
     * @mbggenerated Wed Feb 28 15:52:12 CST 2018
     */
    public void setExpiredAt(Date expiredAt) {
        this.expiredAt = expiredAt;
    }
}